@extends('layouts.main.master')
@section('title')
{{$pageContent->title}}
@endsection
@section('description')
{!!$pageContent->description!!}
@endsection
@section('css')
@endsection
@section('js')
@endsection
@section('content')
ddddđ
@endsection